// Canonical KJV book metadata for the /connections Web of Scripture feature.
// Per-chapter verse counts are in the runtime cross-references.json (generated by scripts/process-cross-refs.ts).
// This file is used for: VerseSearch autocomplete, tooltip display, BookLabels positioning.

export interface BookInfo {
  index: number
  name: string
  abbr: string          // OSIS abbreviation
  displayAbbr: string   // Short display name
  chapters: number
  verseStart: number    // Cumulative verse index (0-based) at start of book
  verseEnd: number      // Cumulative verse index of last verse (inclusive)
  chapterStart: number  // Cumulative chapter index (0-based) at start of book
  testament: 'OT' | 'NT'
  totalVerses: number
}

export const TOTAL_VERSES = 31102   // KJV total (Gen 1:1 = index 0, Rev 22:21 = index 31101)
export const TOTAL_CHAPTERS = 1189  // KJV total chapters

export const BOOKS: BookInfo[] = [
  // ── Old Testament (39 books) ──────────────────────────────────────────────
  { index: 0,  name: 'Genesis',          abbr: 'Gen',    displayAbbr: 'Gen',   chapters: 50,  verseStart: 0,     verseEnd: 1532,  chapterStart: 0,   testament: 'OT', totalVerses: 1533 },
  { index: 1,  name: 'Exodus',           abbr: 'Exod',   displayAbbr: 'Exod',  chapters: 40,  verseStart: 1533,  verseEnd: 2745,  chapterStart: 50,  testament: 'OT', totalVerses: 1213 },
  { index: 2,  name: 'Leviticus',        abbr: 'Lev',    displayAbbr: 'Lev',   chapters: 27,  verseStart: 2746,  verseEnd: 3604,  chapterStart: 90,  testament: 'OT', totalVerses: 859  },
  { index: 3,  name: 'Numbers',          abbr: 'Num',    displayAbbr: 'Num',   chapters: 36,  verseStart: 3605,  verseEnd: 4892,  chapterStart: 117, testament: 'OT', totalVerses: 1288 },
  { index: 4,  name: 'Deuteronomy',      abbr: 'Deut',   displayAbbr: 'Deut',  chapters: 34,  verseStart: 4893,  verseEnd: 5851,  chapterStart: 153, testament: 'OT', totalVerses: 959  },
  { index: 5,  name: 'Joshua',           abbr: 'Josh',   displayAbbr: 'Josh',  chapters: 24,  verseStart: 5852,  verseEnd: 6509,  chapterStart: 187, testament: 'OT', totalVerses: 658  },
  { index: 6,  name: 'Judges',           abbr: 'Judg',   displayAbbr: 'Judg',  chapters: 21,  verseStart: 6510,  verseEnd: 7127,  chapterStart: 211, testament: 'OT', totalVerses: 618  },
  { index: 7,  name: 'Ruth',             abbr: 'Ruth',   displayAbbr: 'Ruth',  chapters: 4,   verseStart: 7128,  verseEnd: 7212,  chapterStart: 232, testament: 'OT', totalVerses: 85   },
  { index: 8,  name: '1 Samuel',         abbr: '1Sam',   displayAbbr: '1 Sam', chapters: 31,  verseStart: 7213,  verseEnd: 8022,  chapterStart: 236, testament: 'OT', totalVerses: 810  },
  { index: 9,  name: '2 Samuel',         abbr: '2Sam',   displayAbbr: '2 Sam', chapters: 24,  verseStart: 8023,  verseEnd: 8717,  chapterStart: 267, testament: 'OT', totalVerses: 695  },
  { index: 10, name: '1 Kings',          abbr: '1Kgs',   displayAbbr: '1 Kgs', chapters: 22,  verseStart: 8718,  verseEnd: 9533,  chapterStart: 291, testament: 'OT', totalVerses: 816  },
  { index: 11, name: '2 Kings',          abbr: '2Kgs',   displayAbbr: '2 Kgs', chapters: 25,  verseStart: 9534,  verseEnd: 10252, chapterStart: 313, testament: 'OT', totalVerses: 719  },
  { index: 12, name: '1 Chronicles',     abbr: '1Chr',   displayAbbr: '1 Chr', chapters: 29,  verseStart: 10253, verseEnd: 11194, chapterStart: 338, testament: 'OT', totalVerses: 942  },
  { index: 13, name: '2 Chronicles',     abbr: '2Chr',   displayAbbr: '2 Chr', chapters: 36,  verseStart: 11195, verseEnd: 12016, chapterStart: 367, testament: 'OT', totalVerses: 822  },
  { index: 14, name: 'Ezra',             abbr: 'Ezra',   displayAbbr: 'Ezra',  chapters: 10,  verseStart: 12017, verseEnd: 12296, chapterStart: 403, testament: 'OT', totalVerses: 280  },
  { index: 15, name: 'Nehemiah',         abbr: 'Neh',    displayAbbr: 'Neh',   chapters: 13,  verseStart: 12297, verseEnd: 12702, chapterStart: 413, testament: 'OT', totalVerses: 406  },
  { index: 16, name: 'Esther',           abbr: 'Esth',   displayAbbr: 'Esth',  chapters: 10,  verseStart: 12703, verseEnd: 12869, chapterStart: 426, testament: 'OT', totalVerses: 167  },
  { index: 17, name: 'Job',              abbr: 'Job',    displayAbbr: 'Job',   chapters: 42,  verseStart: 12870, verseEnd: 13939, chapterStart: 436, testament: 'OT', totalVerses: 1070 },
  { index: 18, name: 'Psalms',           abbr: 'Ps',     displayAbbr: 'Ps',    chapters: 150, verseStart: 13940, verseEnd: 16400, chapterStart: 478, testament: 'OT', totalVerses: 2461 },
  { index: 19, name: 'Proverbs',         abbr: 'Prov',   displayAbbr: 'Prov',  chapters: 31,  verseStart: 16401, verseEnd: 17315, chapterStart: 628, testament: 'OT', totalVerses: 915  },
  { index: 20, name: 'Ecclesiastes',     abbr: 'Eccl',   displayAbbr: 'Eccl',  chapters: 12,  verseStart: 17316, verseEnd: 17537, chapterStart: 659, testament: 'OT', totalVerses: 222  },
  { index: 21, name: 'Song of Solomon',  abbr: 'Song',   displayAbbr: 'Song',  chapters: 8,   verseStart: 17538, verseEnd: 17654, chapterStart: 671, testament: 'OT', totalVerses: 117  },
  { index: 22, name: 'Isaiah',           abbr: 'Isa',    displayAbbr: 'Isa',   chapters: 66,  verseStart: 17655, verseEnd: 18946, chapterStart: 679, testament: 'OT', totalVerses: 1292 },
  { index: 23, name: 'Jeremiah',         abbr: 'Jer',    displayAbbr: 'Jer',   chapters: 52,  verseStart: 18947, verseEnd: 20310, chapterStart: 745, testament: 'OT', totalVerses: 1364 },
  { index: 24, name: 'Lamentations',     abbr: 'Lam',    displayAbbr: 'Lam',   chapters: 5,   verseStart: 20311, verseEnd: 20464, chapterStart: 797, testament: 'OT', totalVerses: 154  },
  { index: 25, name: 'Ezekiel',          abbr: 'Ezek',   displayAbbr: 'Ezek',  chapters: 48,  verseStart: 20465, verseEnd: 21737, chapterStart: 802, testament: 'OT', totalVerses: 1273 },
  { index: 26, name: 'Daniel',           abbr: 'Dan',    displayAbbr: 'Dan',   chapters: 12,  verseStart: 21738, verseEnd: 22094, chapterStart: 850, testament: 'OT', totalVerses: 357  },
  { index: 27, name: 'Hosea',            abbr: 'Hos',    displayAbbr: 'Hos',   chapters: 14,  verseStart: 22095, verseEnd: 22291, chapterStart: 862, testament: 'OT', totalVerses: 197  },
  { index: 28, name: 'Joel',             abbr: 'Joel',   displayAbbr: 'Joel',  chapters: 3,   verseStart: 22292, verseEnd: 22364, chapterStart: 876, testament: 'OT', totalVerses: 73   },
  { index: 29, name: 'Amos',             abbr: 'Amos',   displayAbbr: 'Amos',  chapters: 9,   verseStart: 22365, verseEnd: 22510, chapterStart: 879, testament: 'OT', totalVerses: 146  },
  { index: 30, name: 'Obadiah',          abbr: 'Obad',   displayAbbr: 'Obad',  chapters: 1,   verseStart: 22511, verseEnd: 22531, chapterStart: 888, testament: 'OT', totalVerses: 21   },
  { index: 31, name: 'Jonah',            abbr: 'Jonah',  displayAbbr: 'Jonah', chapters: 4,   verseStart: 22532, verseEnd: 22579, chapterStart: 889, testament: 'OT', totalVerses: 48   },
  { index: 32, name: 'Micah',            abbr: 'Mic',    displayAbbr: 'Mic',   chapters: 7,   verseStart: 22580, verseEnd: 22684, chapterStart: 893, testament: 'OT', totalVerses: 105  },
  { index: 33, name: 'Nahum',            abbr: 'Nah',    displayAbbr: 'Nah',   chapters: 3,   verseStart: 22685, verseEnd: 22731, chapterStart: 900, testament: 'OT', totalVerses: 47   },
  { index: 34, name: 'Habakkuk',         abbr: 'Hab',    displayAbbr: 'Hab',   chapters: 3,   verseStart: 22732, verseEnd: 22787, chapterStart: 903, testament: 'OT', totalVerses: 56   },
  { index: 35, name: 'Zephaniah',        abbr: 'Zeph',   displayAbbr: 'Zeph',  chapters: 3,   verseStart: 22788, verseEnd: 22840, chapterStart: 906, testament: 'OT', totalVerses: 53   },
  { index: 36, name: 'Haggai',           abbr: 'Hag',    displayAbbr: 'Hag',   chapters: 2,   verseStart: 22841, verseEnd: 22878, chapterStart: 909, testament: 'OT', totalVerses: 38   },
  { index: 37, name: 'Zechariah',        abbr: 'Zech',   displayAbbr: 'Zech',  chapters: 14,  verseStart: 22879, verseEnd: 23089, chapterStart: 911, testament: 'OT', totalVerses: 211  },
  { index: 38, name: 'Malachi',          abbr: 'Mal',    displayAbbr: 'Mal',   chapters: 4,   verseStart: 23090, verseEnd: 23144, chapterStart: 925, testament: 'OT', totalVerses: 55   },
  // ── New Testament (27 books) ──────────────────────────────────────────────
  { index: 39, name: 'Matthew',          abbr: 'Matt',   displayAbbr: 'Matt',  chapters: 28,  verseStart: 23145, verseEnd: 24215, chapterStart: 929, testament: 'NT', totalVerses: 1071 },
  { index: 40, name: 'Mark',             abbr: 'Mark',   displayAbbr: 'Mark',  chapters: 16,  verseStart: 24216, verseEnd: 24893, chapterStart: 957, testament: 'NT', totalVerses: 678  },
  { index: 41, name: 'Luke',             abbr: 'Luke',   displayAbbr: 'Luke',  chapters: 24,  verseStart: 24894, verseEnd: 26044, chapterStart: 973, testament: 'NT', totalVerses: 1151 },
  { index: 42, name: 'John',             abbr: 'John',   displayAbbr: 'John',  chapters: 21,  verseStart: 26045, verseEnd: 26923, chapterStart: 997, testament: 'NT', totalVerses: 879  },
  { index: 43, name: 'Acts',             abbr: 'Acts',   displayAbbr: 'Acts',  chapters: 28,  verseStart: 26924, verseEnd: 27930, chapterStart: 1018, testament: 'NT', totalVerses: 1007 },
  { index: 44, name: 'Romans',           abbr: 'Rom',    displayAbbr: 'Rom',   chapters: 16,  verseStart: 27931, verseEnd: 28363, chapterStart: 1046, testament: 'NT', totalVerses: 433  },
  { index: 45, name: '1 Corinthians',    abbr: '1Cor',   displayAbbr: '1 Cor', chapters: 16,  verseStart: 28364, verseEnd: 28800, chapterStart: 1062, testament: 'NT', totalVerses: 437  },
  { index: 46, name: '2 Corinthians',    abbr: '2Cor',   displayAbbr: '2 Cor', chapters: 13,  verseStart: 28801, verseEnd: 29057, chapterStart: 1078, testament: 'NT', totalVerses: 257  },
  { index: 47, name: 'Galatians',        abbr: 'Gal',    displayAbbr: 'Gal',   chapters: 6,   verseStart: 29058, verseEnd: 29206, chapterStart: 1091, testament: 'NT', totalVerses: 149  },
  { index: 48, name: 'Ephesians',        abbr: 'Eph',    displayAbbr: 'Eph',   chapters: 6,   verseStart: 29207, verseEnd: 29361, chapterStart: 1097, testament: 'NT', totalVerses: 155  },
  { index: 49, name: 'Philippians',      abbr: 'Phil',   displayAbbr: 'Phil',  chapters: 4,   verseStart: 29362, verseEnd: 29465, chapterStart: 1103, testament: 'NT', totalVerses: 104  },
  { index: 50, name: 'Colossians',       abbr: 'Col',    displayAbbr: 'Col',   chapters: 4,   verseStart: 29466, verseEnd: 29560, chapterStart: 1107, testament: 'NT', totalVerses: 95   },
  { index: 51, name: '1 Thessalonians',  abbr: '1Thess', displayAbbr: '1 Th', chapters: 5,   verseStart: 29561, verseEnd: 29649, chapterStart: 1111, testament: 'NT', totalVerses: 89   },
  { index: 52, name: '2 Thessalonians',  abbr: '2Thess', displayAbbr: '2 Th', chapters: 3,   verseStart: 29650, verseEnd: 29696, chapterStart: 1116, testament: 'NT', totalVerses: 47   },
  { index: 53, name: '1 Timothy',        abbr: '1Tim',   displayAbbr: '1 Tim', chapters: 6,   verseStart: 29697, verseEnd: 29809, chapterStart: 1119, testament: 'NT', totalVerses: 113  },
  { index: 54, name: '2 Timothy',        abbr: '2Tim',   displayAbbr: '2 Tim', chapters: 4,   verseStart: 29810, verseEnd: 29892, chapterStart: 1125, testament: 'NT', totalVerses: 83   },
  { index: 55, name: 'Titus',            abbr: 'Titus',  displayAbbr: 'Titus', chapters: 3,   verseStart: 29893, verseEnd: 29938, chapterStart: 1129, testament: 'NT', totalVerses: 46   },
  { index: 56, name: 'Philemon',         abbr: 'Phlm',   displayAbbr: 'Phlm',  chapters: 1,   verseStart: 29939, verseEnd: 29963, chapterStart: 1132, testament: 'NT', totalVerses: 25   },
  { index: 57, name: 'Hebrews',          abbr: 'Heb',    displayAbbr: 'Heb',   chapters: 13,  verseStart: 29964, verseEnd: 30266, chapterStart: 1133, testament: 'NT', totalVerses: 303  },
  { index: 58, name: 'James',            abbr: 'Jas',    displayAbbr: 'Jas',   chapters: 5,   verseStart: 30267, verseEnd: 30374, chapterStart: 1146, testament: 'NT', totalVerses: 108  },
  { index: 59, name: '1 Peter',          abbr: '1Pet',   displayAbbr: '1 Pet', chapters: 5,   verseStart: 30375, verseEnd: 30479, chapterStart: 1151, testament: 'NT', totalVerses: 105  },
  { index: 60, name: '2 Peter',          abbr: '2Pet',   displayAbbr: '2 Pet', chapters: 3,   verseStart: 30480, verseEnd: 30540, chapterStart: 1156, testament: 'NT', totalVerses: 61   },
  { index: 61, name: '1 John',           abbr: '1John',  displayAbbr: '1 Jn',  chapters: 5,   verseStart: 30541, verseEnd: 30645, chapterStart: 1159, testament: 'NT', totalVerses: 105  },
  { index: 62, name: '2 John',           abbr: '2John',  displayAbbr: '2 Jn',  chapters: 1,   verseStart: 30646, verseEnd: 30658, chapterStart: 1164, testament: 'NT', totalVerses: 13   },
  { index: 63, name: '3 John',           abbr: '3John',  displayAbbr: '3 Jn',  chapters: 1,   verseStart: 30659, verseEnd: 30672, chapterStart: 1165, testament: 'NT', totalVerses: 14   },
  { index: 64, name: 'Jude',             abbr: 'Jude',   displayAbbr: 'Jude',  chapters: 1,   verseStart: 30673, verseEnd: 30697, chapterStart: 1166, testament: 'NT', totalVerses: 25   },
  { index: 65, name: 'Revelation',       abbr: 'Rev',    displayAbbr: 'Rev',   chapters: 22,  verseStart: 30698, verseEnd: 31101, chapterStart: 1167, testament: 'NT', totalVerses: 404  },
]

// Build a fast lookup map from OSIS abbreviation to book index
export const ABBR_TO_INDEX: Record<string, number> = {}
for (const book of BOOKS) {
  ABBR_TO_INDEX[book.abbr] = book.index
}

// Index of the first NT book (Matthew) — used for OT/NT divider x-position
export const NT_START_BOOK_INDEX = 39

/**
 * Resolve a verse index (0–31101) back to a human-readable reference.
 * Returns { book, chapter, verse } — all 1-based for chapter and verse.
 * Requires the chapters array from the runtime CrossReferenceData.
 */
export function resolveVerseIndex(
  verseIndex: number,
  chapters: { book: number; chapter: number; verseCount: number; verseStart: number }[]
): { book: BookInfo; chapter: number; verse: number } | null {
  if (verseIndex < 0 || verseIndex >= TOTAL_VERSES) return null

  // Binary search on chapters array
  let lo = 0
  let hi = chapters.length - 1
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1
    if (chapters[mid].verseStart <= verseIndex) {
      lo = mid
    } else {
      hi = mid - 1
    }
  }
  const ch = chapters[lo]
  return {
    book: BOOKS[ch.book],
    chapter: ch.chapter,
    verse: verseIndex - ch.verseStart + 1,
  }
}

/**
 * Format a resolved verse reference as a readable string.
 * e.g. { book: Daniel, chapter: 7, verse: 13 } → "Dan 7:13"
 */
export function formatVerseRef(
  verseIndex: number,
  chapters: { book: number; chapter: number; verseCount: number; verseStart: number }[]
): string {
  const resolved = resolveVerseIndex(verseIndex, chapters)
  if (!resolved) return `[${verseIndex}]`
  return `${resolved.book.displayAbbr} ${resolved.chapter}:${resolved.verse}`
}
